# Generated by Django 4.2.2 on 2023-07-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zob_posts', '0005_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zob_posts.post')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collab_posts', to=settings.AUTH_USER_MODEL)),
                ('og_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_posts', to='zob_posts.post')),
                ('track_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_track_posts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('zob_posts.post',),
        ),
    ]
