# Generated by Django 4.2.2 on 2023-07-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zob_posts', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
