# Generated by Django 4.2.2 on 2023-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zob_artists', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
